spring:
  datasource:
    url: jdbc:mysql://localhost:3306/stockmanagement?createDatabaseIfNotExist=true&userSSL=false&useUnicode=true&useJDBCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: someone
    password: someone
    driver-class-name: com.mysql.cj.jdbc.Driver

# Specify DBMS
  jpa:
    database: MYSQL
    show-sql: false
# Hibernate DDL Auto ( create, create-drop, update)
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
server:
  port: 8081

