spring:
  datasource:
    url: jdbc:mysql://localhost:3306/stockmanagement?createDatabaseIfNotExist=true&userSSL=false&useUnicode=true&useJDBCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: someone
    password: someone
    driver-class-name: com.mysql.cj.jdbc.Driver

# Specify DBMS
  jpa:
    database: MYSQL
    show-sql: false
# Hibernate DDL Auto ( create, create-drop, update)
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
server:
  port: 8081

flickr:
  apiKey: 70eb7d019e15a474c80a8bdde25e4c54
  apiSecret: ec1765b78b4ad4dc
  appKey: 72157720836969209-aa5b2052ef151cb9
  appSecret: eacf151b646f9210